"""End-to-end demo — the whole loop, zero dependencies, zero data vendor.

    python3 demo.py [--bars N] [--seed S] [--trials T]

IT RUNS ON A RANDOM WALK, ON PURPOSE. There is no structure in this data. None.
It is generated by a seeded random number generator and the increments are
independent by construction, so every pattern the scanner finds is a coincidence
and the correct verdict on all of them is no.

That is the demonstration. A system you can only watch agree with you tells you
nothing; watch this one refuse data that has nothing in it, and the refusals it
gives your real data mean something. Section 5 goes further and measures the
false-positive rate directly: it runs the whole pipeline over many independent
random series and counts how often a pattern comes back TRADEABLE on noise.

To point it at real data, replace `random_walk` with your own OHLC bars. Nothing
else changes — and read `CostModel` first, because the default costs are a guess
at your broker rather than your broker.
"""

from __future__ import annotations

import math
import random
import sys
from collections import Counter

from engine.backtest import run
from engine.costs import CostModel
from engine.stats import sample_size_report, trades_to_separate
from engine.verdict import judge, judge_planned
from models.patterns import DETECTORS, Bar, Detection, scan

#: The synthetic bars are hourly-sized (sigma ~ 8 pips a bar), so 24 of them
#: make one financing rollover. Leaving this at the default of 1 would charge
#: 24 nights of swap for every day held -- which made the first run of this
#: demo look more conservative than it had any right to.
BARS_PER_NIGHT = 24

#: Not a broker's published spread: the ALL-IN round turn, and a swap markup
#: that has to be measured rather than assumed. Both are deliberately at the
#: cheap end, so nothing below can be dismissed as a pessimistic cost model.
COSTS = CostModel(pair="EURUSD", round_turn_pips=1.1, swap_markup_annual=0.008)


#: Drift for the positive control. Calibrated, not picked: it roughly DOUBLES
#: the price over the sample, which is about three times faster than the
#: strongest trend EURUSD has ever had (0.85 in 2000 to 1.60 in 2008, over
#: eight years). The first value tried here was 0.0006, which compounds to
#: nine thousand times the starting price and reports +70,777 pips a trade --
#: a control so absurd it proves nothing except that the arithmetic runs.
CONTROL_DRIFT = 0.00004


def trending(n: int, seed: int, drift: float = CONTROL_DRIFT, **kw) -> list:
    """A series with real structure in it — the positive control.

    Watching a refusal engine refuse noise proves only that it refuses. A
    filter that says no to everything is indistinguishable from one that is
    stuck, so it has to be shown passing something it should pass — and the
    something has to be plausible, or the test is theatre.
    """
    return random_walk(n, seed, drift=drift, **kw)


def random_walk(n: int, seed: int, start: float = 1.1000,
                sigma: float = 0.0008, substeps: int = 4,
                drift: float = 0.0) -> list:
    """OHLC bars with independent increments — the null hypothesis, drawn.

    Each bar's high and low come from an intrabar path rather than being made
    up, so the ranges behave like real ones and the ambiguous-bar problem in
    `backtest.py` shows up here exactly as it would on a live series.
    """
    rng = random.Random(seed)
    bars, px, s = [], start, sigma / math.sqrt(substeps)
    for _ in range(n):
        o = px
        path = [o]
        for _ in range(substeps):
            px *= math.exp(rng.gauss(drift / substeps, s))
            path.append(px)
        bars.append(Bar(o, max(path), min(path), px))
    return bars


def _verdicts(bars: list, costs: CostModel) -> dict:
    """Detect, backtest and judge every pattern independently.

    `n_hypotheses` counts the whole search: six detectors times the four
    declared parameters in `models/patterns.py`. Judging each pattern against
    its own hypothesis alone would be the multiple-testing error this engine
    exists to avoid, and it is the reason section 5 has anything to report.
    """
    n_hyp = len(DETECTORS) * 4
    out = {}
    for name, fn in DETECTORS.items():
        res = run(bars, fn(bars), costs, bars_per_night=BARS_PER_NIGHT)
        out[name] = judge(res, costs, name=name, n_hypotheses=n_hyp,
                          costs_confirmed=True)
    return out


def main(bars_n: int = 60_000, seed: int = 11, trials: int = 25) -> None:
    print(__doc__.split("\n\n")[2].strip(), "\n")

    # 1. the data ------------------------------------------------------------
    bars = random_walk(bars_n, seed)
    lo = min(b.l for b in bars)
    hi = max(b.h for b in bars)
    print(f"1. DATA   {bars_n:,} random-walk bars, seed {seed}, "
          f"range {lo:.4f}-{hi:.4f}")
    print(f"   costs  {COSTS.round_turn_pips} pip round turn, "
          f"{COSTS.swap_markup_annual:.1%}/yr swap markup\n")

    # 2. what the scanner finds in noise --------------------------------------
    found = Counter(d.name for d in scan(bars))
    print("2. PATTERNS FOUND IN DATA THAT HAS NONE")
    for name in DETECTORS:
        print(f"   {name:<20} {found.get(name, 0):>6,}")
    print(f"   {'total':<20} {sum(found.values()):>6,}   "
          f"— a scanner always finds patterns; that is not evidence\n")

    # 3. the verdicts ---------------------------------------------------------
    vs = _verdicts(bars, COSTS)
    print("3. VERDICTS")
    print(f"   {'pattern':<20} {'n':>6} {'win%':>6} {'need%':>6} "
          f"{'pips/trade':>11}  verdict")
    for name, v in vs.items():
        head = "TRADEABLE" if v.tradeable else (v.codes[0] if v.codes else "-")
        print(f"   {name:<20} {v.n_trades:>6,} {v.gross.win_rate:>6.1%} "
              f"{v.win_rate_needed:>6.1%} {v.net.net:>11.2f}  {head}")
    print()

    # 4. one verdict in full --------------------------------------------------
    worst = min(vs.values(), key=lambda v: v.net.net if v.n_trades else 0.0)
    print("4. ONE OF THEM IN FULL")
    for line in worst.summary().split("\n"):
        print("   " + line)
    print()

    # 5. how often noise passes -----------------------------------------------
    print(f"5. FALSE POSITIVES — the whole pipeline over {trials} independent "
          f"random series")
    free = CostModel(pair="EURUSD", round_turn_pips=0.0, swap_markup_annual=0.0)
    n_hyp = len(DETECTORS) * 4
    tally = Counter()
    total = 0
    for t in range(trials):
        noise = random_walk(bars_n // 4, 5000 + t)
        for name, fn in DETECTORS.items():
            det = fn(noise)          # detect once, price twice
            total += 1
            for label, cm in (("paid", COSTS), ("free", free)):
                res = run(noise, det, cm, bars_per_night=BARS_PER_NIGHT)
                # judged twice: against the whole search, and as though this
                # pattern were the only hypothesis anyone had ever tried
                for tag, nh in (("corrected", n_hyp), ("naive", 1)):
                    if judge(res, cm, name=name, n_hypotheses=nh,
                             costs_confirmed=True).tradeable:
                        tally[(label, tag)] += 1
    print(f"   {'':<26} {'corrected':>10} {'judged alone':>14}   of {total}")
    print(f"   {'at the costs above':<26} {tally[('paid','corrected')]:>10} "
          f"{tally[('paid','naive')]:>14}")
    print(f"   {'at zero cost':<26} {tally[('free','corrected')]:>10} "
          f"{tally[('free','naive')]:>14}")
    pc, pn = tally[("paid", "corrected")], tally[("paid", "naive")]
    fc, fn = tally[("free", "corrected")], tally[("free", "naive")]
    print(f"   A costless backtest, judging one hypothesis at a time, calls "
          f"{fn / total:.0%} of tests on")
    print(f"   PURE NOISE tradeable. Realistic costs cut that to {pn}. The "
          f"multiple-testing")
    print(f"   correction cuts it to {pc}. Costs are the bigger filter, which "
          f"is why they are")
    print("   module one of this engine and not a footnote at the end.")
    if pc:
        print(f"   AND {pc} SURVIVE BOTH, on data guaranteed to have nothing in "
              f"it. That is not a bug")
        print("   in the correction; it is the limit written into "
              "edge_t_stat(): the t-test treats")
        print("   trades as independent and these overlap heavily, since the "
              "same bars generate")
        print("   many of them. Take a passing t-stat here as a floor on doubt, "
              "never as proof.")
        print("   Out-of-sample data is the only thing that settles it.")
    elif fc:
        print(f"   Nothing survived both, though {fc} survived the correction "
              f"once costs were removed.")
    up = trending(bars_n // 4, 99)
    move = up[-1].c / up[0].o
    print(f"   POSITIVE CONTROL — the same pipeline on a series that DOES "
          f"trend ({up[0].o:.4f} to")
    print(f"   {up[-1].c:.4f}, x{move:.2f} over the sample — about three times "
          f"faster than the strongest")
    print("   trend EURUSD has ever had, so this is generous, not realistic):")
    hits = [f"{n} ({v.n_trades} trades, {v.net.net:+.1f} pips)"
            for n, v in _verdicts(up, COSTS).items() if v.tradeable]
    print(f"   {', '.join(hits) if hits else 'nothing passed — the filter may be stuck'}")
    print("   It has to be shown passing something, or being broken and "
          "refusing everything")
    print("   look exactly the same from outside.")
    print()

    # 6. priced before anything is backtested ---------------------------------
    print("6. WHAT A PLAN NEEDS, BEFORE ANY CODE IS WRITTEN")
    print(f"   {'target/stop':>14} {'payoff':>7} {'needs':>7} {'cost share':>11}")
    for tgt, stp in ((5, 5), (10, 10), (20, 20), (50, 50), (100, 50), (25, 50)):
        d = Detection("double_top", 0, 1, 1.1000,
                      1.1000 - stp * 0.0001, 1.1000 + tgt * 0.0001)
        p = judge_planned(d, COSTS, costs_confirmed=True)
        print(f"   {f'{tgt}/{stp} pips':>14} {d.planned_payoff:>7.2f} "
              f"{p.win_rate_needed:>7.1%} {p.net.cost_penalty_points:>11.1%}")
    print("   The cost penalty is largest on the small-target, high-win-rate")
    print("   plans that 'highest win rate' leads you to. That is the trap.\n")

    # 7. and how long it would take to know -----------------------------------
    print("7. HOW LONG BEFORE A CLAIM MEANS ANYTHING")
    for wr, be in ((0.60, 0.50), (0.55, 0.50), (0.52, 0.50)):
        print(f"   {sample_size_report(wr, be, 520).split(' — ')[0]}"
              f" — {trades_to_separate(wr, be) / 52:.1f} years at one a week")
    print()
    print("Nothing above was trading advice. It was a demonstration that this")
    print("engine says no to noise, which is the only reason to believe it when")
    print("it says no — or yes — to yours.")


if __name__ == "__main__":
    a = sys.argv[1:]
    def opt(flag, default):
        return int(a[a.index(flag) + 1]) if flag in a else default
    main(bars_n=opt("--bars", 60_000), seed=opt("--seed", 11),
         trials=opt("--trials", 25))
